#config_version=5

show_player:
  mode_attract_started: 
   attract_light_show:
     speed: 4

slides:
  dmd_slide_1:
  - type: text
    text: Play Ball!
    font_size: 30
    color: f87217

slide_player:
  mode_attract_started:
    dmd_slide_1:
      target: dmd