#config_version=5
mode:
  start_events: ball_starting
  priority: 100

variable_player:
  s_left_pop_bumper_active:
    score: 10
  s_right_pop_bumper_active:
    score: 10
  s_center_pop_bumper_active:
    score: 10
  s_bumpers_active:
    score: 10
  s_left_slingshot_active:
    score: 10
  s_right_slingshot_active:
    score: 10
  s_left_target_1_active:
    score: 10
  s_left_target_2_active:
    score: 10
  s_left_target_3_active:
    score: 10
  s_right_target_1_active:
    score: 10
  s_right_target_2_active:
    score: 10
  s_right_target_3_active:
    score: 10
  s_lower_target_1_active:
    score: 10
  s_lower_target_3_active:
    score: 10
  s_single_lanes_active:
    score: 100
  s_double_lanes_active:
    score: 200
  s_triple_lanes_active:
    score: 300
  s_home_run_lanes_active:
    score: 500
  s_right_vt_100_active:
    score: 100
    events_when_activated: reset_right_varitarget
  s_right_vt_200_active:
    score: 200
    events_when_activated: reset_right_varitarget
  s_right_vt_300_active:
    score: 300
    events_when_activated: reset_right_varitarget
  s_right_vt_500_active:
    score: 500
    events_when_activated: reset_right_varitarget
  s_left_vt_100_active:
    score: 100
    events_when_activated: reset_left_varitarget
  s_left_vt_200_active:
    score: 200
    events_when_activated: reset_left_varitarget
  s_left_vt_300_active:
    score: 300
    events_when_activated: reset_left_varitarget
  s_left_vt_500_active:
    score: 500
    events_when_activated: reset_left_varitarget